language: ruby
sudo: false

cache: bundler 

before_install: gem update bundler

install:
  - bundle install

script:
  - "./travis.sh"

branches:
  only:
    - master

env:
  global:
    secure: "jvGDSekQgza0i6d5zLOjDMlQyyb1y7ln4TTlDVW7RqwuhZcqAIdq2m1eiUpY8t19ThSnmSUW54lqmA4na+H4FpuOzDEM4gcWRKEiwksovdKacFPcA1GKFKZONkAYQ9ZNQb2iT5sfjvNtM86mkHjIrq05JZjZGEgXzHHpIhAuJv/z1XPtz0sihg8bKzdQWxDbWI+JEs3soeuXNJW+BoZU2Rum3bmqcEvqmZNS6iZsNl+nkynk4XwjsqsG7sWSSlW3YNw/8K3J5GU8ANwtMN+Bv6iZR9CCEITmyBOoDXVmnDAuaZQYBoHEUY1gC1p/rIRfa8QDUi3zmF6uN0YI85mqYlFlyx6nJygaJu/gU7RIwvESVljrsvUHdYB3ov3cH7yyfFfQjSpGiOQsFRsdFmhp83IuPto/+KZL13KEMskI3OhYSUMQMr9bCOPbAvatLY9I65RdLNwfpnh3jM4lwDMM/PliZDBIDmOWkAcLxvm31/sZ0TCvSnKcb/iOuehnNeLkB47oPvdYFT6une2Tx+hxdcZpZ5tOEJI/s5uhLmRwEWkhpLpTIL2bBRfOiCQsBspwxk9Go0bGqKNvz6ewf+DBY3l9sa9grn5cFv0J2TUj+uTI5ehfJoIdmoPpLFtQ2sc5v7o16Pic4+ktdDECkzwnohz4NIApxRw77WkyWwy5nFY="
