title: CODECHECK
#email: your-email@example.com
description: >-
  CODECHECK is a process for independent execution of computations underlying scholarly research articles.
baseurl: ""
url: "https://codecheck.org.uk"
author: "Stephen Eglen & Daniel Nüst"

markdown: kramdown
remote_theme: aterenin/minima-reboot

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from

license:
  text: CC BY-SA 4.0
  link: https://creativecommons.org/licenses/by-sa/4.0/
  logo: /img/by-sa.svg

# https://github.com/aterenin/minima-reboot/#adding-new-links-to-footer
# Possible icon source: https://gitlab.com/gitlab-org/gitlab-svgs/-/tree/main/sprite_icons
footer_icons:
  - username: Team
    url: mailto:team@cdchck.science
    icon: icon-email.svg
  - username: github.com/codecheckers
    url: https://github.com/codecheckers/
    icon: icon-github.svg
  - username: gitlab.com/cdchck
    url: https://gitlab.com/cdchck
    icon: icon-gitlab.svg
  #- username: sje30
  #  url: https://github.com/sje30/
  #  icon: icon-github.svg
  #- username: nuest
  #  url: https://github.com/nuest/
  #  icon: icon-github.svg
  #- username: StephenEglen
  #  url: https://twitter.com/StephenEglen
  #  icon: icon-twitter.svg
  #- username: nordholmen
  #  url: https://twitter.com/nordholmen
  #  icon: icon-twitter.svg
  - username: codecheck@fediscience.org
    url: https://fediscience.org/@codecheck
    icon: icon-mastodon.svg
  - username: linkedin.com/company/codecheck/
    url: https://www.linkedin.com/company/codecheck/
    icon: icon-linkedin.svg
  - username: youtube.com/@cdchck
    url: https://www.youtube.com/@cdchck
    icon: icon-youtube.svg
  - username: Team
    url: mailto:team@cdchck.science
    icon: icon-email.svg

header_pages:
  - project.md
  - process.md
  - workflows.md
  - partners.md
  - get-involved.md

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - docker-compose.yml
  - travis.sh
  - .travis.yml
  - Makefile
  - logo
  - badge
  - .git

error_mode: strict
