title: CODECHECK
#email: your-email@example.com
description: >-
  CODECHECK is a process for independent execution of computations underlying scholarly research articles.
baseurl: ""
url: "https://codecheck.org.uk"
author: "Stephen Eglen & Daniel Nüst"

markdown: kramdown
remote_theme: aterenin/minima-reboot

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from

license:
  text: CC BY-SA 4.0
  link: https://creativecommons.org/licenses/by-sa/4.0/
  logo: /img/by-sa.svg

# https://github.com/aterenin/minima-reboot/#adding-new-links-to-footer
footer_icons:
  - username: github.com/codecheckers
    url: https://github.com/codecheckers/
    icon: icon-github.svg
  - username: gitlab.com/cdchck
    url: https://gitlab.com/cdchck
    icon: icon-gitlab.svg
  #- username: sje30
  #  url: https://github.com/sje30/
  #  icon: icon-github.svg
  #- username: nuest
  #  url: https://github.com/nuest/
  #  icon: icon-github.svg
  #- username: StephenEglen
  #  url: https://twitter.com/StephenEglen
  #  icon: icon-twitter.svg
  #- username: nordholmen
  #  url: https://twitter.com/nordholmen
  #  icon: icon-twitter.svg
  - username: codecheck@fediscience.org
    url: https://fediscience.org/@codecheck
    icon: icon-mastodon.svg
  - username: youtube.com/@cdchck
    url: https://www.youtube.com/@cdchck
    icon: icon-youtube.svg
  - username: S. Eglen
    url: mailto:sje30@cam.ac.uk
    icon: icon-email.svg
  - username: D. Nüst
    url: mailto:daniel.nuest@tu-dresden.de
    icon: icon-email.svg

header_pages:
  - project.md
  - process.md
  - partners.md
  - get-involved.md

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - docker-compose.yml
  - travis.sh
  - .travis.yml
  - Makefile
  - logo
  - badge

error_mode: strict
